routes/web.php
<?php

use Illuminate\Support\Facades\Session;
use App\Http\Helpers\AppHelper;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::group(['middleware' => 'role:admin'], function() {
//    Route::get('/admin', function() {
//        return 'Welcome Admin';
//    });
//});
Route::get('/clear-cache', function() {

       Artisan::call('cache:clear');
   Artisan::call('config:clear');
   Artisan::call('config:cache');
   Artisan::call('view:clear');

   return "Cleared!".env('DB_DATABASE');
});



/**
 * Admin panel routes goes below
 */
Route::group(
    ['namespace' => 'Backend', 'middleware' => ['guest']], function () {
    Route::get('/login', 'UserController@login')->name('login');
    Route::get('/register', 'UserController@register')->name('register');
    Route::post('/login', 'UserController@authenticate');
    Route::get('/forgot', 'UserController@forgot')->name('forgot');
    Route::post('/forgot', 'UserController@forgot')
        ->name('forgot');
    Route::get('/reset/{token}', 'UserController@reset')
        ->name('reset');
    Route::post('/reset/{token}', 'UserController@reset')
        ->name('reset');
    Route::post('/storeSignup', 'UserController@storeSignup')
        ->name('storeSignup');
}
);

Route::get('/public/exam', 'Backend\ExamController@indexPublic')->name('public.exam_list');
Route::any('/online-result', 'Backend\ReportController@marksheetPublic')->name('report.marksheet_pub');
Route::resource('jobs', 'Backend\JobsController');
Route::resource('job-requests', 'Backend\JobRequestController');
Route::get('/admission-detail', 'Backend\AdmissionDetailController@index')->name('admission-detail');
Route::get('/admission-detail/{key?}','Backend\AdmissionDetailController@admissionType');
Route::get('/online-admission','Backend\AdmissionDetailController@onlineAdmissionList')->name('online-admission');
Route::get('/online-admission-detail/{id?}','Backend\AdmissionDetailController@onlineAdmissionDetail')->name('online-admission-detail');
Route::get('/showFile','Backend\JobRequestController@showFile');
Route::resource('students', 'Backend\StudentsController');
Route::post('passOut', 'Backend\StudentController@passOut')->name('passOut');
Route::post('deliver-certificate', 'Backend\StudentController@deliverCertificate')->name('deliverCertificate');

/* Route::get('/job/requests', 'Backend\JobRequestController@requestJob')->name('job.requests');
 Route::get('/job/requests/edit', 'Backend\JobRequestController@editJobRequests')->name('job.requests.edit');
 Route::get('/job/requests/destroy/{id}', 'Backend\JobRequestController@deleteJobRequest')->name('job.requests.destroy');*/

Route::group(
    ['namespace' => 'Backend', 'middleware' => ['auth', 'permission']], function () {

    Route::group(['prefix' => 'admin'], function(){
            Route::resource('course', 'CourseController');
            Route::resource('campus', 'CampusController');
    });


    Route::get('/logout', 'UserController@logout')->name('logout');
    Route::get('/lock', 'UserController@lock')->name('lockscreen');
    Route::get('/dashboard', 'UserController@dashboard')->name('user.dashboard');
    Route::resource('slider', 'SliderController');
//    Route::resource('jobs', 'JobsController');

    //user management
    Route::resource('user', 'UserController');
    Route::get('/profile', 'UserController@profile')
        ->name('profile');
    Route::post('/profile', 'UserController@profile')
        ->name('profile');
    Route::get('/change-password', 'UserController@changePassword')
        ->name('change_password');
    Route::post('/change-password', 'UserController@changePassword')
        ->name('change_password');
    Route::post('user/status/{id}', 'UserController@changeStatus')
        ->name('user.status');
    Route::any('user/{id}/permission', 'UserController@updatePermission')
        ->name('user.permission');

    //user notification
    Route::get('/notification/unread', 'NotificationController@getUnReadNotification')
        ->name('user.notification_unread');
    Route::get('/notification/read', 'NotificationController@getReadNotification')
        ->name('user.notification_read');
    Route::get('/notification/all', 'NotificationController@getAllNotification')
        ->name('user.notification_all');

    //system user management
    Route::get('/administrator/user', 'AdministratorController@userIndex')
        ->name('administrator.user_index');
    Route::get('/administrator/user/create', 'AdministratorController@userCreate')
        ->name('administrator.user_create');
    Route::post('/administrator/user/store', 'AdministratorController@userStore')
        ->name('administrator.user_store');
    Route::get('/administrator/user/{id}/edit', 'AdministratorController@userEdit')
        ->name('administrator.user_edit');
    Route::post('/administrator/user/{id}/update', 'AdministratorController@userUpdate')
        ->name('administrator.user_update');
    Route::post('/administrator/user/{id}/delete', 'AdministratorController@userDestroy')
        ->name('administrator.user_destroy');
    Route::post('administrator/user/status/{id}', 'AdministratorController@userChangeStatus')
        ->name('administrator.user_status');

    Route::any('/administrator/user/reset-password', 'AdministratorController@userResetPassword')
        ->name('administrator.user_password_reset');



    //user role manage
    Route::get('/role', 'UserController@roles')
        ->name('user.role_index');
    Route::post('/role', 'UserController@roles')
        ->name('user.role_destroy');
    Route::get('/role/create', 'UserController@roleCreate')
        ->name('user.role_create');
    Route::post('/role/store', 'UserController@roleCreate')
        ->name('user.role_store');
    Route::any('/role/update/{id}', 'UserController@roleUpdate')
        ->name('user.role_update');


    // application settings routes
    Route::get('settings/institute', 'SettingsController@institute')
        ->name('settings.institute');
    Route::post('settings/institute', 'SettingsController@institute')
        ->name('settings.institute');

    // academic calendar
    Route::get('settings/academic-calendar', 'SettingsController@academicCalendarIndex')
        ->name('settings.academic_calendar.index');
    Route::post('settings/academic-calendar', 'SettingsController@academicCalendarIndex')
        ->name('settings.academic_calendar.destroy');
    Route::get('settings/academic-calendar/create', 'SettingsController@academicCalendarCru')
        ->name('settings.academic_calendar.create');
    Route::post('settings/academic-calendar/create', 'SettingsController@academicCalendarCru')
        ->name('settings.academic_calendar.store');
    Route::get('settings/academic-calendar/edit/{id}', 'SettingsController@academicCalendarCru')
        ->name('settings.academic_calendar.edit');
    Route::post('settings/academic-calendar/update/{id}', 'SettingsController@academicCalendarCru')
        ->name('settings.academic_calendar.update');

    //sms gateways
    Route::get('settings/sms-gateway', 'SettingsController@smsGatewayIndex')
        ->name('settings.sms_gateway.index');
    Route::post('settings/sms-gateway', 'SettingsController@smsGatewayIndex')
        ->name('settings.sms_gateway.destroy');
    Route::get('settings/sms-gateway/create', 'SettingsController@smsGatewayCru')
        ->name('settings.sms_gateway.create');
    Route::post('settings/sms-gateway/create', 'SettingsController@smsGatewayCru')
        ->name('settings.sms_gateway.store');
    Route::get('settings/sms-gateway/edit/{id}', 'SettingsController@smsGatewayCru')
        ->name('settings.sms_gateway.edit');
    Route::post('settings/sms-gateway/update/{id}', 'SettingsController@smsGatewayCru')
        ->name('settings.sms_gateway.update');

    //report settings
    Route::get('settings/report', 'SettingsController@report')
        ->name('settings.report');
    Route::post('settings/report', 'SettingsController@report')
        ->name('settings.report');


    // administrator routes
    //academic year
    Route::get('administrator/academic_year', 'AdministratorController@academicYearIndex')
        ->name('administrator.academic_year');
    Route::post('administrator/academic_year', 'AdministratorController@academicYearIndex')
        ->name('administrator.academic_year_destroy');
    Route::get('administrator/academic_year/create', 'AdministratorController@academicYearCru')
        ->name('administrator.academic_year_create');
    Route::post('administrator/academic_year/create', 'AdministratorController@academicYearCru')
        ->name('administrator.academic_year_store');
    Route::get('administrator/academic_year/edit/{id}', 'AdministratorController@academicYearCru')
        ->name('administrator.academic_year_edit');
    Route::post('administrator/academic_year/update/{id}', 'AdministratorController@academicYearCru')
        ->name('administrator.academic_year_update');
    Route::post('administrator/academic_year/status/{id}', 'AdministratorController@academicYearChangeStatus')
        ->name('administrator.academic_year_status');


    // template
    //mail and sms
    Route::get('administrator/template-mailandsms', 'AdministratorController@templateMailAndSmsIndex')
        ->name('administrator.template.mailsms.index');
    Route::post('administrator/template-mailandsms', 'AdministratorController@templateMailAndSmsIndex')
        ->name('administrator.template.mailsms.destroy');
    Route::get('administrator/template-mailandsms/create', 'AdministratorController@templateMailAndSmsCru')

app/Http/Controllers/Backend/AdmissionDetailController.php
<?php

namespace App\Http\Controllers\Backend;

use App\AdmissionDetail;
use App\DegreeProgram;
use App\InstituteJobs;
use App\StudentInquiries;
use App\StudyInstitute;
use App\StudyProgram;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdmissionDetailController extends Controller
{
    public function index(){
        $admission=AdmissionDetail::paginate(env('MAX_RECORD_PER_PAGE',25));
//        $admissionStatus=AdmissionDetail::get()->unique();//dd($admissionStatus->pluck('type'));//pluck('type');//dd($admissionStatus);
        return view('backend.admission-detail.index',compact('admission'));
    }
    public function admissionType($key = null){
        if (!is_null($key)) {
            $admission = AdmissionDetail::where('type', $key)->paginate(env('MAX_RECORD_PER_PAGE',25));//dd($jobs);
            $view = (string)view('backend.admission-detail.partial.admission_detail_row', compact('admission'));

        } else {
            $jobs = [];
            $view = (string)view('backend.admission-detail.partial.admission_detail_row', compact('admission'));
        }
        return response()->json([
            'view' => $view,
            'status' => 'success',
        ]);
    }

    public function onlineAdmissionList(){
        $admission=StudentInquiries::paginate(env('MAX_RECORD_PER_PAGE',25));
        return view('backend.admission-detail.online-admission.index',compact('admission'));

    }
    public function onlineAdmissionDetail($id){
        $admission=StudentInquiries::find($id);
        $institute=StudyInstitute::find($admission->institute);
        $study=StudyProgram::find($admission->study);
        $degree=DegreeProgram::find($admission->degree);

        return view('backend.admission-detail.online-admission.show',compact('admission','institute','study','degree'));

    }
}

app/Http/Controllers/Backend/CampusController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Campus;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class CampusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $campuses = Campus::all();
        return view('backend.campus.list', compact(
            'campuses'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $campus = null;
        $campus_type = null;
        return view('backend.campus.add', compact('campus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules =  [
            'name' => 'required',
            'address' => 'required',
        ];
        $this->validate($request, $rules);

        $data = $request->only('name','address');
        $data['code'] = 'CAM-'.rand(100,200);
        Campus::create($data);

        return redirect()->back()->with('success', 'Campus created!');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param   integer $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $campus = Campus::findOrFail($id);
        return view('backend.campus.add', compact('campus'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param   integer $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $campus = Campus::findOrFail($id);

        $rules =  [
            'name' => 'required',
            'address' => 'required',
        ];
        $this->validate($request, $rules);

        $data = $request->only('name','address');
        $campus->fill($data);
        $campus->save();


        return redirect()->back()->with('success', 'Campus Updated!');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param   integer $id
     * @return \Illuminate\Http\Response
     */
//    public function destroy($id)
//    {
//        $campus = Campus::findOrFail($id);
//        $campus->delete();
//
//        return redirect()->back()->with('success', 'Campus deleted!');
//    }
}

app/Http/Controllers/Backend/JobRequestController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Event;
use App\JobRequests;
use PDF;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Storage;

class JobRequestController extends Controller
{
    public function index(){
        $requestJobs=JobRequests::paginate(env('MAX_RECORD_PER_PAGE',25));
        return view('backend.request_job.index', compact('requestJobs'));
    }
    public function edit($id){
        $request = JobRequests::findOrFail($id);
        return view('backend.request_job.edit', compact('request'));
    }
    public function destroy($id){
        $request = JobRequests::findOrFail($id);
        $request->delete();
        return redirect()->route('job-requests.index')->with('success', 'Job Request deleted.');
    }
    public function show($id){
        $request = JobRequests::findOrFail($id);
//        $filename = asset('storage/job/requests/').$request->photograph;
//        $pdf = PDF::loadView('backend.request_job.show' , compact('request'));
        return view('backend.request_job.show', compact('request'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $jobRequest = JobRequests::findOrFail($id);
        $filename = null;
        if($request->hasFile('photograph')) {
            if($jobRequest->photograph){
                $file_path = "storage/job/requests/".$jobRequest->photograph;
                Storage::delete($file_path);
            }
            $file = $request->file('photograph');
            $destinationPath = public_path('storage/job/requests');
            $filename =   time() . "." . $file->getClientOriginalExtension();
            $file->move($destinationPath, $filename);
            $data['photograph'] = $filename;
        }
        $jobRequest->fill($data);
        $jobRequest->save();
        return redirect()->route('job-requests.index')->with('success', 'Event information updated.');
    }

}

resources/views/backend/courses/list.blade.php
<!-- Master page  -->
@extends('backend.layouts.master')

<!-- Page title -->
@section('pageTitle') Courses @endsection
<!-- End block -->

<!-- Page body extra class -->
@section('bodyCssClass') @endsection
<!-- End block -->

<!-- BEGIN PAGE CONTENT-->
@section('pageContent')
    <!-- Section header -->
    <section class="content-header">
        <h1>
            Courses
            <small>List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{URL::route('user.dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">Courses</li>
        </ol>
    </section>
    <!-- ./Section header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header">
                        <div class="box-tools pull-right">
                            <a class="btn btn-info btn-sm" href="{{ URL::route('course.create') }}"><i class="fa fa-plus-circle"></i> Add New</a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body margin-top-20">
                        <div class="table-responsive">
                        <table id="listDataTableWithSearch" class="table table-bordered table-striped list_view_table display responsive no-wrap" width="100%">
                            <thead>
                            <tr>
                                <th width="5%">#</th>
                                <th class="notexport" width="10%">Code</th>
                                <th>Name</th>
                                <th>Institute</th>
                                <th>Campus</th>
                                <th>Share Group</th>
                                <th>Detail</th>
                                <th class="notexport" width="15%">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($courses as $course)
                                <tr>
                                    <td>
                                        {{$loop->iteration}}
                                    </td>
                                    <td>
                                        {{$course->code}}
                                    </td>
                                    <td>
                                        {{$course->name}}
                                    </td>
                                    <td>
                                        {{$course->institute ? $course->institute->institute : ''}}
                                    </td>
                                    <td>
                                        {{$course->campus ? $course->campus->code.' '.$course->campus->name : ''}}
                                    </td>
                                    <td>
                                        {{$course->share_group_text ? $course->share_group_text : '-- -- --'}}
                                    </td>
                                    <td>
                                        {{str_limit($course->detail, 60)}}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a title="Details"  href="{{URL::route('course.show',$course->id)}}"  class="btn btn-primary btn-sm"><i class="fa fa-eye"></i>
                                            </a>
                                        </div>
                                        <div class="btn-group">
                                            <a title="Edit" href="{{URL::route('course.edit',$course->id)}}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                            </a>
                                        </div>
                                        <div class="btn-group">
                                            <form  class="myAction" method="POST" action="{{URL::route('course.destroy', $course->id)}}">
                                                @csrf
                                                <input name="_method" type="hidden" value="DELETE">
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                                    <i class="fa fa-fw fa-trash"></i>
                                                </button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            @endforeach

                            </tbody>

                        </table>
                    </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection
<!-- END PAGE CONTENT-->

<!-- BEGIN PAGE JS-->
@section('extraScript')
    <script type="text/javascript">
        $(document).ready(function () {
            window.changeExportColumnIndex = 5;
            window.excludeFilterComlumns = [0,1,6,7];
            Generic.initCommonPageJS();
            Generic.initDeleteDialog();
        });
    </script>
@endsection
<!-- END PAGE JS-->

resources/views/backend/courses/view.blade.php
<!-- Master page  -->
@extends('backend.layouts.master')

<!-- Page title -->
@section('pageTitle') Course Detail @endsection
<!-- End block -->

<!-- Page body extra css -->
@section('extraStyle')
    <style>
        @media print {
            @page {
                size:  A4 landscape;
                margin: 5px;
            }
        }
    </style>
@endsection
<!-- End block -->

<!-- BEGIN PAGE CONTENT-->
@section('pageContent')
    <!-- Section header -->
    <section class="content-header">
        <div class="btn-group">
            <a href="#"  class="btn-ta btn-sm-ta btn-print btnPrintInformation"><i class="fa fa-print"></i> Print</a>
        </div>
        <div class="btn-group">
            <a href="{{URL::route('course.edit',$course->id)}}" class="btn-ta btn-sm-ta"><i class="fa fa-edit"></i> Edit</a>
        </div>

        <ol class="breadcrumb">
            <li><a href="{{URL::route('user.dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{URL::route('course.index')}}"><i class="fa icon-course"></i> Course</a></li>
            <li class="active">View</li>
        </ol>
    </section>
    <!-- ./Section header -->
    <!-- Main content -->
    <section class="content main-contents">
        <div class="row">
            <div class="col-md-12">
                <div id="printableArea">
                    <div class="box box-info">
                    <div class="box-body">
                            <div class="row">
                                <div class="col-md-2">
                                    <label for="">Name</label>
                                </div>
                                <div class="col-md-4">
                                    <p for=""> {{$course->name}}</p>
                                </div>
                                <div class="col-md-2">
                                    <label for="">Detail</label>
                                </div>
                                <div class="col-md-4">
                                    <p for=""> {{$course->detail}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <label for="">Institute</label>
                                </div>
                                <div class="col-md-4">
                                    <p for=""> {{$course->institute ? $course->institute->institute : ''}}</p>
                                </div>
                                <div class="col-md-2">
                                    <label for="">Campus</label>
                                </div>
                                <div class="col-md-4">
                                    <p for=""> {{$course->campus ? $course->campus->code.' '.$course->campus->name : ''}}</p>
                                </div>
                            </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label for="">Duration</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->duration}} Days</p>
                            </div>
                            <div class="col-md-2">
                                <label for="">End Date Apply</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->is_end == 0 ? 'No' : \Carbon\Carbon::parse($course->end_date)->format('d-m-Y')}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label for="">Group Share Name</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->share_group_text}}</p>
                            </div>
                            <div class="col-md-2">
                                <label for="">Group Share %</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->share_group_value}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label for="">Registration Fee</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->registration_fee}}</p>
                            </div>
                            <div class="col-md-2">
                                <label for="">Admission Fee</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->admission_fee}}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <label for="">Test Fee</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->test_fee}}</p>
                            </div>
                            <div class="col-md-2">
                                <label for="">Tuition Fee</label>
                            </div>
                            <div class="col-md-4">
                                <p for=""> {{$course->tution_fee}}</p>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection
<!-- END PAGE CONTENT-->

<!-- BEGIN PAGE JS-->
@section('extraScript')
    <script type="text/javascript">
        $(document).ready(function () {
            $('.btnPrintInformation').click(function () {
                $('ul.nav-tabs li:not(.active)').addClass('no-print');
                $('ul.nav-tabs li.active').removeClass('no-print');
                window.print();
            });
        });
    </script>
@endsection
<!-- END PAGE JS-->